### ISSUE TITLE
Citation for use of the Coregistration-Qgis-processing plugin

### ISSUE THREAD

**Issue by patrchristen** [SMByC/Coregistration-Qgis-processing#12]
Hi,
I used the QGIS-plugin to coregister multiple PRISMA scenes to a Sentinel-2 scene. I want to cite both the AROSICS algorithm as well as this plugin. So I'd like to ask how and whom to cite for the plugin?

Best regards.

**Comment by XavierCLL** [comment]
Hi,
Yeah you need to cite both, here is an idea of how to cite this plugin:

Llano, X. (2024), SMByC-IDEAM. Coregistration Qgis processing plugin for image co-registration, version 24.6. Available in https://github.com/SMByC/Coregistration-Qgis-processing

**Comment by patrchristen** [comment]
Hi, 
Thank you for the quick response.
