### ISSUE TITLE
Allow output in formats beside GTiff

### ISSUE THREAD

**Issue by chippey** [SMByC/Coregistration-Qgis-processing#14]
In global and local registrations that use arosics, I get errors when trying to output in something besides a geotiff (eg. ENVI).  I see in the lines you call arosics COREG, you have the output format hard-coded to GTIFF (`fmt_out="GTiff"`).  Could that be changed to support the other gdal formats available in arosics?

**Comment by XavierCLL** [comment]
Hi @chippey 

That makes sense, I'm going to implement/fix that. Thanks so much for detecting and reporting this

**Comment by XavierCLL** [comment]
Hi @chippey 

Could you do some tests with the new version 24.12?

Thanks!

**Comment by chippey** [comment]
@XavierCLL Sure!  I'll have to do it later tonight though

Cheers!

**Comment by XavierCLL** [comment]
Implemented in version 24.12. I personally tested but if you have a chance to test it too, it would be great.
