### ISSUE TITLE
Local co-registration - use a larger matching window size as default

### ISSUE THREAD

**Issue by danschef** [SMByC/Coregistration-Qgis-processing#2]
The default matching window size for the local co-registration is set to 256x256 pixels in AROSICS. This is because the accuracy of the computed shifts strongly depends on the window size of the moving window which is used to compute a grid of tie points. When using a too small window size, the accuracy is quite bad, leading to residual registration errors in the result. I recommend to stick to the default value here.

**Comment by XavierCLL** [comment]
oh! perfect, thanks @danschef 

Then `window_size=256x256` and what is your recommendation for `grid_res` value by default?

**Comment by danschef** [comment]
Well, that depends on the size of the input datasets. If the input image is like 8000x8000 pixels and the size is set to 100, AROSICS has to compute 8000/100*8000/100=6400 tie points which might already take a while on some machines. So far, AROSICS lets the user decide on this with regard to computational resources and image size. But I think I will implement something into AROSICS that auto-computes a meaningful value.
