### ISSUE TITLE
Use cubic resampling as default resampling technique.

### ISSUE THREAD

**Issue by danschef** [SMByC/Coregistration-Qgis-processing#3]
Currently (version 21.11.18), the default is set to nearest neighbour resampling which might cause a somewhat pixelated output. Users might be disappointed from that, so I recommend to use cubic resampling as default. Apart from that, nearest neighbour can cause geometric errors up to half a pixel (which is already visible).

**Comment by XavierCLL** [comment]
Thanks @danschef 

yeah, I read something about it in your documentation, the question is if uses cubic resampling as default for both algorithms? or only for local?

**Comment by danschef** [comment]
The issue is the same for global and local co-registration. But global co-registration will not resample the dataset as long as the user does not want the output grid to be aligned to the reference or target image. So I would use cubic for both.
